[package]
name = "free_enc"
version = "0.1.0"
authors = ["jb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.16.20"
data-encoding = "2.3.2"
aes = "0.6.0"
block-modes = "0.7.0"
gost-modes = "0.4.0"